language: csharp
mono: none
dotnet: 3.1 
solution: FlowerShop.sln
script:
  - dotnet publish --configuration Release --runtime win-x64 -p:PublishSingleFile=true --output win-x64
  - dotnet publish --configuration Release --runtime win-x86 -p:PublishSingleFile=true --output win-x86
  - dotnet publish --configuration Release --runtime linux-x64 -p:PublishSingleFile=true --output linux-x64
before_deploy:
- zip -r9 win-x64.zip win-x64
- zip -r9 win-x86.zip win-x86
- zip -r9 linux-x64.zip linux-x64
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file:
  - win-x64.zip
  - win-x86.zip
  - linux-x64.zip
on:
  tags: true
  branches:
    only:
      - master